#!/bin/sh

/etc/init.d/shorewall stop
/etc/init.d/iptables stop
/etc/init.d/ip6tables stop

iptables -L
ip6tables -L

if [ ! -e /etc/sysconfig/network-scripts/ifcfg-dummy0 ] ; then
   echo "Manual ifconfig..."
   ifconfig dummy0 down
   # Achtung: Multicast-Flag muß gesetzt werden, sonst wird das
   #          Interface für sendMulticastOverAllInterfaces() nicht genutzt!
   ifconfig dummy0 10.255.255.1 netmask 255.255.255.0 up multicast
   ip addr add 2000:1:2:3:4:5:6:7/64 dev dummy0
   # ip addr add fec0:1:2:3:4:5:6:7/64 dev dummy0
   # ip addr add fec1:9:8:7:6:5:4:3/64 dev dummy0
else
   ifup dummy0
fi

route add default gw 10.255.255.200
route --inet6 add default gw 2000:1:2:3:4:5:6:7777
