#!/bin/bash
# $Id$
# --------------------------------------------------------------------------
#
#              //===//   //=====   //===//   //       //   //===//
#             //    //  //        //    //  //       //   //    //
#            //===//   //=====   //===//   //       //   //===<<
#           //   \\         //  //        //       //   //    //
#          //     \\  =====//  //        //=====  //   //===//    Version II
#
# ------------- An Efficient RSerPool Prototype Implementation -------------
#
# Copyright (C) 2002-2008 by Thomas Dreibholz
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
# Contact: dreibh@iem.uni-due.de


# dummy0 abschalten
ip addr flush dev dummy0
ip link set dummy0 down

# Achtung: Multicast-Flag muß gesetzt werden, sonst wird das
#          Interface für sendMulticastOverAllInterfaces() nicht genutzt!
ip link set dummy0 up multicast on


# IPv4-Adresse
ip addr add 10.255.255.1/24 dev dummy0

# IPv6-Adresse
# ip addr add 3ffe:ab:cd:ef:123:45:67:89a/64 dev dummy0


# IPv4-Adresse und Route; Default-Metrik: 0
# ip route add metric 0xffff default via 10.255.255.2

# IPv6-Adresse und Route; Default-Metrik: 1024
# ip route add metric 0xffff default via 3ffe:ab:cd:ef:aabb:ccdd:dead:beef

# Zeige Routingtabellen
# ip -f link route
