#!/bin/sh

if [ -e /etc/init.d/shorewall ] ; then
   /etc/init.d/shorewall stop
fi
if [ -e /etc/init.d/iptables ] ; then
   /etc/init.d/iptables stop
fi
if [ -e /etc/init.d/ip6tables ] ; then
   /etc/init.d/ip6tables stop
fi

iptables -L
ip6tables -L

if [ ! -e /etc/sysconfig/network-scripts/ifcfg-dummy0 ] ; then
   echo "Manual ifconfig..."
   ifconfig dummy0 down
   # Achtung: Multicast-Flag muß gesetzt werden, sonst wird das
   #          Interface für sendMulticastOverAllInterfaces() nicht genutzt!
   ifconfig dummy0 10.255.255.1 netmask 255.255.255.0 up multicast
   ip addr add 3ffe:1:2:3:4:5:6:7/64 dev dummy0
   # ip addr add fec0:1:2:3:4:5:6:7/64 dev dummy0
   # ip addr add fec1:9:8:7:6:5:4:3/64 dev dummy0
else
   ifup dummy0
fi

route add default gw 10.255.255.200
route --inet6 add default gw 3ffe:1:2:3:4:5:6:7777
