#!/bin/bash
#
# Thomas Dreibholz's PlanetLab Script Collection
# Copyright (C) 2005-2006 by Thomas Dreibholz, dreibh@exp-math.uni-essen.de
#
# $Id: go 959 2006-02-23 12:57:18Z dreibh $
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA 02111-1307, USA.
#
# Contact: dreibh@iem.uni-due.de
#

. ./planetlab-config


if [ $# -ne 1 ]; then
   echo "Usage: combine-vectors [Test ID]"
   exit 1
fi
TESTID=$1
shift


if [ ! -e $TESTID/ ]; then
   mkdir $TESTID/
fi
cd $TESTID/

PU_VECTORS=`ls $TESTID-pu*.vec.bz2`

(
   for v in $PU_VECTORS ; do
      echo "--values=$v"
      echo "--input=$v"
   done
) | ../combinesummaries pu-vectors.vec.bz2 "Host" -quiet
