#!/bin/bash

. ./planetlab-config

make && ./create-binaries && \
ls p?-*.hosts | xargs -n 1 cat | grep "^[a-Z0-9]" | sort -u | xargs ./do-clearall && \
ls p?-*.hosts | xargs -n 1 cat | grep "^[a-Z0-9]" | sort -u | xargs ./install-binaries
