#!/bin/bash

. ./planetlab-config

MAX_GOOD=5
PUs=15
PEs=6
PRs=1



get-hosts ()
{
   GH_OUTPUT=""
   i=0 ; while [ $i -lt $GH_AMOUNT ] ; do
      j=0;
      for host in $goodhosts ; do
         if [ $j -lt $MAX_GOOD ] ; then
            GH_OUTPUT="$GH_OUTPUT $host"
            let i=$i+1
            if [ $i -ge $GH_AMOUNT ]; then
               return
            fi
         fi
         let j=$j+1
      done
   done
}

test-hosts ()
{
   hosts=`echo $IN_HOSTS | xargs -n1 echo | sort -u`
   goodhosts=`echo $hosts | xargs -x ./exectime "./filter-hosts >/dev/null"`

   if [ "x$goodhosts" = "x" ] ; then
      echo "ERROR: No good hosts found!"
      exit 1
   fi

   GH_GOODHOSTS=$goodhosts
   GH_AMOUNT=$PUs
   get-hosts
   OUT_PUs=$GH_OUTPUT

   GH_AMOUNT=$PEs
   get-hosts
   OUT_PEs=$GH_OUTPUT

   GH_AMOUNT=$PRs
   get-hosts
   OUT_PRs=$GH_OUTPUT

   echo "PRs: $OUT_PRs"
   echo "PEs: $OUT_PEs"
   echo "PUs: $OUT_PUs"
   write-hosts
}

write-hosts ()
{
   ( echo $OUT_PUs | xargs -n1 ) >pu-$HOSTSFILEMIDDLE.hosts
   ( echo $OUT_PEs | xargs -n1 ) >pe-$HOSTSFILEMIDDLE.hosts
   ( echo $OUT_PRs | xargs -n1 ) >pr-$HOSTSFILEMIDDLE.hosts
}

get-all-good-hosts ()
{
   echo "# Hosts list created on `date`" >$OUT_HOSTS
   hosts=`echo $IN_HOSTS | xargs -n1 echo | sort -u`
   for host in $hosts ; do
      echo "Trying $host ..."
      result=`./filter-hosts $host`
      if [ "x$result" != "x" ] ; then
         echo $result >>$OUT_HOSTS
      fi
   done
}



IN_HOSTS="`grep ".uni-essen.de$" all-planetlab.hosts`"
HOSTSFILEMIDDLE="essen"
test-hosts

IN_HOSTS="`grep ".de$" all-planetlab.hosts`"
HOSTSFILEMIDDLE="europe"
test-hosts

IN_HOSTS="`grep ".berkeley.edu$" all-planetlab.hosts` `grep ".ucla.edu$" all-planetlab.hosts` `grep ".ucsd.edu$" all-planetlab.hosts`"
HOSTSFILEMIDDLE="america"
test-hosts

IN_HOSTS="`grep ".jp$" all-planetlab.hosts`"
HOSTSFILEMIDDLE="asia"
test-hosts

IN_HOSTS="`grep ".au$" all-planetlab.hosts`"
let SERVER_TEST_TIMEOUT=5*$SERVER_TEST_TIMEOUT
HOSTSFILEMIDDLE="australia"
test-hosts



# echo "Testing *all* nodes sequentially. This will take a long time ..."
# . ./planetlab-config
# IN_HOSTS="`cat all-planetlab.hosts`"
# OUT_HOSTS=planetlab.hosts
# let SERVER_TEST_TIMEOUT=10*$SERVER_TEST_TIMEOUT
# get-all-good-hosts
