.\" $Id$
.\" --------------------------------------------------------------------------
.\"
.\"              //===//   //=====   //===//   //       //   //===//
.\"             //    //  //        //    //  //       //   //    //
.\"            //===//   //=====   //===//   //       //   //===<<
.\"           //   \\         //  //        //       //   //    //
.\"          //     \\  =====//  //        //=====  //   //===//    Version II
.\"
.\" ------------- An Efficient RSerPool Prototype Implementation -------------
.\"
.\" Copyright (C) 2002-2013 by Thomas Dreibholz
.\"
.\" This program is free software: you can redistribute it and/or modify
.\" it under the terms of the GNU General Public License as published by
.\" the Free Software Foundation, either version 3 of the License, or
.\" (at your option) any later version.
.\"
.\" This program is distributed in the hope that it will be useful,
.\" but WITHOUT ANY WARRANTY; without even the implied warranty of
.\" MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
.\" GNU General Public License for more details.
.\"
.\" You should have received a copy of the GNU General Public License
.\" along with this program.  If not, see <http://www.gnu.org/licenses/>.
.\"
.\" Contact: dreibh@iem.uni-due.de
.\"
.\" ###### Setup ############################################################
.Dd June 06, 2012
.Dt CSPMonitor 1
.Os CSP Monitor
.\" ###### Name #############################################################
.Sh NAME
.Nm cspmonitor
.Nd CSP server for monitoring RSerPool components
.\" ###### Synopsis #########################################################
.Sh SYNOPSIS
.Nm cspmonitor
.Op Fl localaddress=address:port
.Op Fl updateinterval=milliseconds
.Op Fl purgeinterval=milliseconds
.Op Fl compact
.Op Fl full
.Op Fl maxpr=PRs
.Op Fl maxpe=PEs
.Op Fl maxpu=PUs
.Op Fl maxlocationsize=characters
.Op Fl logappend=filename
.Op Fl logcolor=on|off
.Op Fl logfile=filename
.Op Fl loglevel=0-9
.\" ###### Description ######################################################
.Sh DESCRIPTION
.Nm cspmonitor
is a simple simple Component Status Protocol (CSP) monitor server. It receives
status messages from components via UDP and prints them on the screen. This
program is useful to keep an overview of running RSerPool components.
.Pp
.\" ###### Arguments ########################################################
.Sh ARGUMENTS
The following options are available:
.Bl -tag -width indent
.It Fl localaddress=address:port
Sets the local UDP socket address and port number. By default, it listens on
all addresses, port 2960.
.It Fl updateinterval=milliseconds
Sets the update interval in milliseconds. Default: 1000.
.It Fl purgeinterval=milliseconds
Sets the purge interval in milliseconds. Default: 30000.
.It Fl compact
Turns on compact status display mode.
.It Fl full
Turns on full status display mode (default).
.It Fl maxpr=PRs
Limits the number of PRs to be displayed to the given number.
.It Fl maxpr=PEs
Limits the number of PEs to be displayed to the given number.
.It Fl maxpr=PUs
Limits the number of PUs to be displayed to the given number.
.It Fl maxlocationsize=characters
Limits the location string size to the given number of characters.
.\" ====== Logging ==========================================================
.It Logging Parameters:
.Bl -tag -width indent
.It Fl logappend=filename
Write logging output to a file (default is stdout); output will be appended to given file.
.It Fl logcolor=on|off
Turns ANSI colorization of the logging output on or off.
.It Fl logfile=filename
Write logging output to a file (default is stdout); given file will be overwritten.
.It Fl loglevel=0-9
Sets the logging verbosity from 0 (none) to 9 (very verbose).
It is recommended to use at least a value of 2 to see possibly
important error messages and warnings.
.El
.El
.Pp
.\" ###### Environment ######################################################
.Sh ENVIRONMENT
.Nm cspmonitor
uses the environment variables CSP_SERVER and CSP_INTERVAL to define a CSP
server to send reports to in the specified interval.
.\" ###### Diagnostics ######################################################
.Sh DIAGNOSTICS
If loglevel>0, log messages will be printed to stdout or into a specified
log file.
.\" ###### See also #########################################################
.Sh SEE ALSO
For a detailed introduction to RSerPool, see:
.br
http://duepublico.uni-duisburg-essen.de/servlets/DerivateServlet/Derivate-16326/Dre2006-final.pdf
.Pp
Thomas Dreibholz's RSerPool Page:
.br
http://www.iem.uni-due.de/~dreibh/rserpool/
