#!/bin/bash

. ./planetlab-config


showbad=0
showhosts=0


SERVER_TEST_OUTPUT=/dev/null
SERVER_LIST=""
while [ x$1 != "x" ] ; do \
   arg=`echo $1 | grep -- "^-"`
   if [ "x$arg" = "x" ] ; then
      SERVER_LIST="$SERVER_LIST $1"
   else
      if [ "x$1" = "x-showbad" ] ; then
         showbad=1
      elif [ "x$1" = "x-showhosts" ] ; then
         showhosts=1
      elif [ "x$1" = "x-showoutput" ] ; then
         SERVER_TEST_OUTPUT=/dev/stderr
      else
         echo "ERROR: Bad parameter $1"
         exit 1
      fi
   fi
   shift
done
SERVER_LIST=`echo $SERVER_LIST | xargs -xn1 | sort -u`


good=0
bad=0
for SERVER in $SERVER_LIST; do
   isgood=0
   if [ $showhosts = 1 ] ; then
      echo "# Testing $SERVER ..."
   fi
   ./execalarm $SERVER_TEST_TIMEOUT "ssh -C -i $PLANETLAB_KEY -oStrictHostKeyChecking=no -oPasswordAuthentication=no $PLANETLAB_USER@$SERVER \"$SERVER_TEST && echo \\\"$SERVER is ready!\\\"\"" 1>$SERVER_TEST_OUTPUT 2>$SERVER_TEST_OUTPUT
   result=$?
   if [ $result -eq 0 ]  ; then
      isgood=1
   fi

   if [ $isgood = 1 ] ; then
      echo "$SERVER"
      let "good+=1"
   else
      if [ $showbad = 1 ] ; then
         echo "# --- $SERVER"
      fi
      let "bad+=1"
   fi
done

if [ $showbad = 1 ] ; then
   echo "# Good: $good   Bad: $bad"
fi

if [ $bad -gt 0 ] ; then
   exit 1
fi
