#!/bin/bash

. ./planetlab-config

TESTID=fractal-scenario2

PR_LIST=`cat pe-america.hosts pe-europe.hosts|grep "^[a-Z0-9]"|sort -u`   # ACHTUNG: Eindeutigkeit unbedingt notwendig!!!
PE_LIST=`cat planetlab.hosts|grep "^[a-Z0-9]"|sort -u`
#PE_LIST=`cat pe-europe.hosts|grep "^[a-Z0-9]"|sort -u`

PR_MISCOPT="-cspinterval=5000 -loglevel=4"
PE_MISCOPT="-cspinterval=0000 -fractal -fgpfailureafter=0 -rereginterval=30000 -policy=RoundRobin -loglevel=3 "


resetAll ()
{
   ./stop-processes Registrar
   ./stop-processes PoolElement
}

startNetwork ()
{
   optPeers=""
   for peer in $PR_LIST ; do
      optPeers="$optPeers -peer=$peer:3864"
   done
   number=1
   for pr in $PR_LIST ; do
      echo "Starting PR on $pr ..."
      ./start-process "Registrar-$number" "./rootshell -c \"./registrar $OPT_CSP $PR_MISCOPT -identifier=100$number -asap=0.0.0.0:3863 -enrp=0.0.0.0:3864 $optPeers \" >$TESTID-pr$number-$pr.log 2>&1" $pr &
      let number=$number+1
   done

   optRegistrars=""
   for pr in $PR_LIST ; do
      optRegistrars="$optRegistrars -registrar=$pr:3863"
   done
   number=1
   for pe in $PE_LIST ; do
      echo "Starting PE on $pe ..."
      ./start-process "PoolElement-$number" "./rootshell -c \"./server $OPT_CSP $PE_MISCOPT $optRegistrars -identifier=$number \" >$TESTID-pe$number-$pe.log 2>&1" $pe &
      let number=$number+1
   done
}

stopNetwork ()
{
   number=1
   for pe in $PE_LIST ; do
      ./stop-process "PoolElement-$number" $pe
      let number=$number+1
   done
   number=1
   for pr in $PR_LIST ; do
      ./stop-process "Registrar-$number" $pr
      let number=$number+1
   done
}



if [ $# -lt 1 ] ; then
   echo "Usage: fractal-scenario2 [start|stop|reset|user]"
fi

if [ "x$1" = "xstart" ] ; then
   startNetwork
elif [ "x$1" = "xstop" ] ; then
   stopNetwork
elif [ "x$1" = "xreset" ] ; then
   echo "Resetting everything!"
   resetAll
elif [ "x$1" = "xuser" ] ; then
   optRegistrars=""
   for pr in $PR_LIST ; do
      optRegistrars="$optRegistrars -registrar=$pr:3863"
   done
   ./fractalpooluser $optRegistrars -loglevel=1 $OPT_CSP
else
   echo "ERROR: Bad parameter!"
fi
