#!/bin/bash

. ./planetlab-config


SERVER=$1
if [ x$SERVER = "x" ]; then
   echo "ERROR: No server name/IP given!"
   exit 1
fi

scp -rC -i $PLANETLAB_KEY -oPasswordAuthentication=no $PLANETLAB_USER@$1 $2
