#!/bin/bash
echo ""
echo ""
echo "######################################################################"
echo "NOTE: The nameserver is now named \"registrar\"!"
echo "Usage of \"nameserver\" is deprecated, this script will be removed soon!"
echo "######################################################################"
echo ""
echo ""
./registrar $@
