#!/bin/bash
#
# Thomas Dreibholz's PlanetLab Script Collection
# Copyright (C) 2005-2006 by Thomas Dreibholz, dreibh@exp-math.uni-essen.de
#
# $Id: install-binaries 1435 2007-06-05 13:20:58Z dreibh $
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA 02111-1307, USA.
#
# Contact: dreibh@iem.uni-due.de
#

PLANETLAB_KEY=~/.ssh/planetlab
PLANETLAB_USER=due_test
PLANETLAB_COMPILEHOST="planetlab1.exp-math.uni-essen.de"   # "planet5.cs.huji.ac.il" "planetlab2.exp-math.uni-essen.de" "planetlab1.exp-math.uni-essen.de" "planetlab15.millennium.berkeley.edu"
PLANETLAB_YUMOPTS="--disablerepo=ThirdParty"
PLANETLAB_COMPILEPKGS="libtool gdb automake autoconf joe libstdc++-devel gcc gcc-c++ glib-devel glib2-devel make subversion libpcap bzip2-devel slocate"

DISTNAME="rsplib-2.4.0beta1"
DISTDIRNAME="rsplib"
DISTCONFOPT="--enable-csp --disable-qt"
DISTPRGS="registrar server calcappclient hsdump rootshell"
KILLALLMISC="perftool bzip2 gzip tar yum /usr/bin/python /usr/bin/yum"
DISTSTRIP=0
DISTMISC=""
SUIDPRGS="registrar server calcappclient hsdump rootshell"

OPT_CSP="-cspserver=132.252.150.151:2960 -cspinterval=1000"


SCTPLIB_DIRECTORY="/home/dreibh/src/sctplib1"
SCTPLIB_OPT="--enable-sctp-over-udp --enable-static --disable-shared --enable-maintainer-mode"
SOCKETAPI_DIRECTORY="/home/dreibh/src/socketapi"
SOCKETAPI_OPT="--enable-sctp-over-udp --enable-static --disable-shared --enable-maintainer-mode"


# Auf dem Server zum Test ausführen
# Ping + 16 MBytes /dev/urandom + SHA1 => 9s auf Athlon 1.3GHz
SERVER_TEST_TIMEOUT=36
SERVER_TEST="ping -W5 -c1 www.planet-lab.org && dd if=/dev/urandom of=test.data count=16000 bs=1000 && sha1sum test.data && rm -f test.data"
