#!/bin/bash

. ./planetlab-config


SERVER=$1
if [ x$SERVER = "x" ]; then
   echo "ERROR: No server name/IP given!"
   exit 1
fi


while [ ! x$1 = "x" ] ; do
   SERVER=$1
   shift

   echo -e "\x1b[34m`date`: Contacting $SERVER ...\x1b[0m"

   cmd="echo \"\`date\`: Installing packages on $SERVER ...\""
   first=0
   for i in $PLANETLAB_COMPILEPKGS ; do
      if [ $first -eq 0 ] ; then
         cmd="$cmd ; echo sudo yum -y install $i"
      else
         cmd="$cmd ; echo sudo yum -y -C install $i"
      fi
      first=1
   done
   cmd="$cmd ; echo \"\`date\`: $SERVER is ready!\""
   #echo $cmd

   ssh -C -i $PLANETLAB_KEY -oPasswordAuthentication=no $PLANETLAB_USER@$SERVER "$cmd" &
done

wait
