#!/bin/bash

. ./planetlab-config


SERVER=$1
if [ x$SERVER = "x" ]; then
   echo "ERROR: No server name/IP given!"
   exit 1
fi


SERVER_LIST=`\
( \
while [ x$1 != "x" ] ; do \
   echo $1 && \
   shift ; \
done \
) | sort -u`



for SERVER in $SERVER_LIST; do
   echo -e "\x1b[34m`date`: Contacting $SERVER ...\x1b[0m"

   cmd="echo \"\`date\`: Installing packages on $SERVER ...\""
   first=0
   for i in $PLANETLAB_COMPILEPKGS ; do
      if [ $first -eq 0 ] ; then
         cmd="$cmd ; sudo yum -y install $i"
      else
         cmd="$cmd ; sudo yum -y -C install $i"
      fi
      first=1
   done
   cmd="$cmd ; sudo yum -y -C update ; sudo yum -y -C upgrade ; sudo updatedb ; echo \"\`date\`: $SERVER is ready!\""
   #echo $cmd

   ssh -C -i $PLANETLAB_KEY -oPasswordAuthentication=no $PLANETLAB_USER@$SERVER "$cmd" &
done

wait
