#!/bin/sh

CSPCONFIG=""
if [ x$CSP_SERVER != "x" ] ; then
   if [ x$CSP_INTERVAL != "x" ] ; then
      if [ $CSP_INTERVAL -gt 0 ] ; then
         echo "Using CSP server $CSP_SERVER with interval $CSP_INTERVAL ms..."
         export CSPCONFIG="-cspserver=$CSP_SERVER -cspinterval=$CSP_INTERVAL"
      fi
   fi
fi

./registrar -asap=auto -asapannounce=[ff05::3863]:3863 -enrp=auto -enrpmulticast=[ff05::3864]:3864 -maxbadpereports=99999999 -logcolor=on -loglevel=3 $CSPCONFIG $@
