.\" $Id$
.\" ###### Setup ############################################################
.Dd June 07, 2012
.Dt RspRegistrar 1
.Os RSerPool Registrar
.\" ###### Note #############################################################
.Sh NAME
.Nm registrar
.Nd registrar has been renamed to rspregistrar in rsplib-3.0.0!
