#!/bin/bash

runSets="X2 X3"
for run in $runSets ; do
   M1ID="messung6A-$run"
   M2ID="messung6B-$run"
   PR="-loglevel=3 -distancestep=75"
   M1PE="-poolhandle=PoolOne -calcapp -rereginterval=3333 -policy=LeastUsedDPF:0.00001 -capmaxjobs=5 -loglevel=3"
   M2PE="-poolhandle=PoolTwo -calcapp -rereginterval=3333 -policy=LeastUsed -capmaxjobs=5 -loglevel=3"
   M1PU="-poolhandle=PoolOne -jobinterval=10 -jobsize=1000000 -loglevel=3"
   M2PU="-poolhandle=PoolTwo -jobinterval=10 -jobsize=1000000 -loglevel=3"


   # ------ Registrars ------------------------------------------------------
   echo "`date` ========== $M1ID/$M2ID: Phase S1 - Starting PRs =========="
   ./test5 "$M1ID" "$PR" "$M1PE" "$M1PU" start europe pr
   ./test5 "$M1ID" "$PR" "$M1PE" "$M1PU" start america pr
   ./test5 "$M1ID" "$PR" "$M1PE" "$M1PU" start asia pr
   sleep 20

   # ------ PEs -------------------------------------------------------------
   echo "`date` ========== $M1ID/$M2ID: Phase S2 - Starting PEs =========="
   ./test5 "$M1ID" "$PR" "$M1PE" "$M1PU" start europe pe 5
   ./test5 "$M1ID" "$PR" "$M1PE" "$M1PU" start america pe 5
   ./test5 "$M1ID" "$PR" "$M1PE" "$M1PU" start asia pe 5

   ./test5 "$M2ID" "$PR" "$M2PE" "$M2PU" start europe pe 5
   ./test5 "$M2ID" "$PR" "$M2PE" "$M2PU" start america pe 5
   ./test5 "$M2ID" "$PR" "$M2PE" "$M2PU" start asia pe 5
   sleep 45

   # ------ PUs -------------------------------------------------------------
   echo "`date` ========== $M1ID/$M2ID: Phase S3 - Starting PUs =========="
   ./test5 "$M1ID" "$PR" "$M1PE" "$M1PU" start europe pu 15
   ./test5 "$M1ID" "$PR" "$M1PE" "$M1PU" start america pu 15
   ./test5 "$M1ID" "$PR" "$M1PE" "$M1PU" start asia pu 15

   ./test5 "$M2ID" "$PR" "$M2PE" "$M2PU" start europe pu 15
   ./test5 "$M2ID" "$PR" "$M2PE" "$M2PU" start america pu 15
   ./test5 "$M2ID" "$PR" "$M2PE" "$M2PU" start asia pu 15

   # ========================================================================


   echo "`date` ========== $M1ID/$M2ID: Phase T1 - Normal operation =========="
   sleep 300

#    echo "`date` ========== $M1ID/$M2ID: Phase T2 - Failure in Asia =========="
#    ./test5 "$M2ID" "$PR" "$M2PE" "$M2PU" stop asia pe 2
#    ./test5 "$M1ID" "$PR" "$M1PE" "$M1PU" stop asia pe 2
#    sleep 900
#
#    echo "`date` ========== $M1ID/$M2ID: Phase T3 - Activating backup capacity =========="
#    ./test5 "$M1ID" "$PR" "$M1PE" "$M1PU" start america pe 6
#    ./test5 "$M1ID" "$PR" "$M1PE" "$M1PU" start europe pe 6
#    ./test5 "$M2ID" "$PR" "$M2PE" "$M2PU" start america pe 6
#    ./test5 "$M2ID" "$PR" "$M2PE" "$M2PU" start europe pe 6
#    sleep 900
#
#    echo "`date` ========== $M1ID/$M2ID: Phase T4 - Recovered PEs in Asia =========="
#    ./test5 "$M1ID" "$PR" "$M1PE" "$M1PU" start asia pe 5
#    ./test5 "$M2ID" "$PR" "$M2PE" "$M2PU" start asia pe 5
#    sleep 300
#
#    echo "`date` ========== $M1ID/$M2ID: Phase T5 - Back to normal operation =========="
#    ./test5 "$M1ID" "$PR" "$M1PE" "$M1PU" stop america pe 1
#    ./test5 "$M1ID" "$PR" "$M1PE" "$M1PU" stop europe pe 1
#    ./test5 "$M2ID" "$PR" "$M2PE" "$M2PU" stop america pe 1
#    ./test5 "$M2ID" "$PR" "$M2PE" "$M2PU" stop europe pe 1
#    sleep 900


   # ========================================================================

   # ------ Shutdown --------------------------------------------------------
   echo "`date` ========== $M1ID/$M2ID: Phase E1 - Stopping all components  =========="
   ./test5 "$M2ID" "$PR" "$M2PE" "$M2PU" stop europe pu
   ./test5 "$M2ID" "$PR" "$M2PE" "$M2PU" stop america pu
   ./test5 "$M2ID" "$PR" "$M2PE" "$M2PU" stop asia pu

   ./test5 "$M1ID" "$PR" "$M1PE" "$M1PU" stop europe pu
   ./test5 "$M1ID" "$PR" "$M1PE" "$M1PU" stop america pu
   ./test5 "$M1ID" "$PR" "$M1PE" "$M1PU" stop asia pu
   sleep 2

   ./test5 "$M2ID" "$PR" "$M2PE" "$M2PU" stop europe pe
   ./test5 "$M2ID" "$PR" "$M2PE" "$M2PU" stop america pe
   ./test5 "$M2ID" "$PR" "$M2PE" "$M2PU" stop asia pe

   ./test5 "$M1ID" "$PR" "$M1PE" "$M1PU" stop europe pe
   ./test5 "$M1ID" "$PR" "$M1PE" "$M1PU" stop america pe
   ./test5 "$M1ID" "$PR" "$M1PE" "$M1PU" stop asia pe
   sleep 2

   ./test5 "$M1ID" "$PR" "$M1PE" "$M1PU" stop europe pr
   ./test5 "$M1ID" "$PR" "$M1PE" "$M1PU" stop america pr
   ./test5 "$M1ID" "$PR" "$M1PE" "$M1PU" stop asia pr
   sleep 2

   # ------ Get results -----------------------------------------------------
   echo "`date` ========== $M1ID/$M2ID: Phase E2 - Fetching results  =========="
   rm -rf $M1ID/
   rm -rf $M2ID/
   ./test5 "$M1ID" "$PR" "$M1PE" "$M1PU" results
   ./test5 "$M2ID" "$PR" "$M2PE" "$M2PU" results
done
