#!/bin/bash

# ./test1 start all
# sleep 3600
# ./test1 stop all
# ./test1 results
#
# ./test2 start all
# sleep 3600
# ./test2 stop all
# ./test2 results


./test3 start europe pr
./test3 start america pr
./test3 start asia pr
sleep 60
./test3 start europe pe 5
./test3 start america pe 5
./test3 start asia pe 5
sleep 60
./test3 start europe pu 15
./test3 start america pu 15
./test3 start asia pu 15
sleep 900
./test3 stop asia pe 2
sleep 900
./test3 start europe pe 6
./test3 start america pe 6
sleep 900
./test3 start asia pe 5
sleep 300
./test3 stop europe pe 1
./test3 stop america pe 1
sleep 900
./test3 stop all
./test3 results


# sleep 3600
# ./test3 stop all
# ./test3 results

# R --vanilla <plot-test1.R
# scp test1.pdf svn:

#./test1 start all
