#!/bin/bash

# ./test1a start
# sleep 3600
# ./test1a stop
# ./test1a results
#
# ./test1b start
# sleep 3600
# ./test1b stop
# ./test1b results
#
# ./test1c start
# sleep 3600
# ./test1c stop
# ./test1c results

./test2 start
sleep 3600
./test2 stop
./test2 results

./test3 start
sleep 3600
./test3 stop
./test3 results

#./test1 start
