#!/bin/bash
# $Id$
# --------------------------------------------------------------------------
#
#              //===//   //=====   //===//   //       //   //===//
#             //    //  //        //    //  //       //   //    //
#            //===//   //=====   //===//   //       //   //===<<
#           //   \\         //  //        //       //   //    //
#          //     \\  =====//  //        //=====  //   //===//    Version II
#
# ------------- An Efficient RSerPool Prototype Implementation -------------
#
# Copyright (C) 2002-2009 by Thomas Dreibholz
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
# Contact: dreibh@iem.uni-due.de


CPUs=`cat /proc/cpuinfo 2>/dev/null|grep "^processor"|wc --lines`
if [ $CPUs -lt 1 ] ; then
   CPUs=1
fi

echo "CPUs=$CPUs ..."
./server -scripting -ssmaxthreads=$CPUs -cspserver=132.252.151.151:2960 -cspinterval=1000 -policy=LeastUsedDegradation:0.25 -loglevel=3 -registrar=[2001:638:501:4ef4:201:2ff:fef1:84dc]:3863 -registrar=[2001:638:501:4ef3:211:43ff:febb:cee0]:3863 -cspserver=132.252.150.151 >pe.log 2>&1 $@
