#!/bin/bash

. ./planetlab-config

if [ $# -lt 3 ]; then
   echo "Usage: start-registrar [Registrars File] [Options] [Server 1] {Server 2} ..."
   exit 1
fi


REGISTRARS_FILE=$1
OPT_OTHER="-asap=0.0.0.0:3863 -enrp=0.0.0.0:3864 $2"
shift
shift

if [ ! -e "$REGISTRARS_FILE" ]; then
   echo "ERROR: No registrars file \"$REGISTRARS_FILE\" found!"
   exit 1
fi
OPT_REGISTRARS=`cat $REGISTRARS_FILE | xargs -i§ -n1 echo -n '-peer=§:3864 '`



PROCNAME="registrar"
PROGCALL="sudo ~/bin/registrar $OPT_REGISTRARS $OPT_OTHER"
PROGCHK=0

. ./start-process $@
