#!/bin/bash
#
# Thomas Dreibholz's PlanetLab Script Collection
# Copyright (C) 2005-2006 by Thomas Dreibholz, dreibh@exp-math.uni-essen.de
#
# $Id$
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA 02111-1307, USA.
#
# Contact: dreibh@iem.uni-due.de
#

. ./planetlab-config

if [ $# -ne 1 ]; then
   echo "Usage: start-processes [Process Name]"
   exit 1
fi
PROCNAME=$1
shift


PIDFILES=`find . -name \"$PROCNAME-*.pid\"`
for PIDFILE in $PIDFILES; do
   PID=`cat $PIDFILE`
   if ps -p `cat $PIDFILE` | grep ssh 1>/dev/null 2>/dev/null ; then
      echo "Processing $PIDFILE: sending SIGINT to $PID ..."
      kill $PID
   else
      echo "Processing $PIDFILE: process is already gone."
   fi
   rm $PIDFILE
done
