.\" $Id$
.\" ###### Setup ############################################################
.Dd June 06, 2012
.Dt RspTerminal 1
.Os RSerPool Terminal
.\" ###### Note #############################################################
.Sh NAME
.Nm terminal
.Nd terminal has been renamed to rspterminal in rsplib-3.0.0!
