#!/bin/bash

# INPUT="U01 U02 U03 U04 U05 U06 U07 U08 U09 U10 U11 U12"
INPUT="V00 V01 V03 V04 V05 V06 V07 V08 V09 V10 V11 V12 V13 V14 V15 V16 V17 V18 V19 V20"
OUTPUT="journal2006"

(
for m in $INPUT ; do
   echo "--values=$m LeastUsedDPF"
   echo "--input=messung-disaster1A-$m/pu-vectors.vec.bz2"
   echo "--values=$m LeastUsed"
   echo "--input=messung-disaster1B-$m/pu-vectors.vec.bz2"
done
) | ../combinesummaries $OUTPUT.data.bz2 "Measurement Policy"
