#!/bin/bash
# $Id$
#
# Thomas Dreibholz's PlanetLab Script Collection
# Copyright (C) 2005-2008 by Thomas Dreibholz
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
# Contact: dreibh@iem.uni-due.de


# Settings for "location":
NorthAmerica=1
Europe=2
Australasia=3
SouthAmerica=4


DNSWorking="(dns1udp<80 || dns2udp<80)"
DNSFine="(dns1udp<20 && dns2udp<80)"

DiskOkay="(gbfree>=5)"
MemOkay="((freemem >= 100)  && (swapused <= 10))"

TimeOkay="(drift <= 1000ms)"
TimeFine="(drift <= 1ms)"

LoadOkay="(5minload < 5)"
LoadFine="(5minload < 1)"


AliveHost="((resptime > 0) && (sshstatus < 1h) && $DNSWorking)"
GoodHost="($AliveHost && $DiskOkay && $MemOkay && $LoadOkay)"
GreatHost="($GoodHost && $DNSFine && $LoadFine)"

CandidateForPU="($GoodHost && $TimeOkay)"
CandidateForPE="($GoodHost && $TimeOkay)"
CandidateForPR="($GreatHost && $TimeFine)"


./comon-query alive-planetlab.hosts "$AliveHost" name name nameonly quiet

./comon-query pr-europe.hosts "$CandidateForPR && location==$Europe" name 5minload nameonly quiet
./comon-query pr-asia.hosts "$CandidateForPR && location==$Australasia" name 5minload nameonly quiet
./comon-query pr-america.hosts "$CandidateForPR && (location==$NorthAmerica || location==$SouthAmerica)" name 5minload nameonly quiet

./comon-query pe-europe.hosts "$CandidateForPE && location==$Europe" name 5minload nameonly quiet
./comon-query pe-asia.hosts "$CandidateForPE && location==$Australasia" name 5minload nameonly quiet
./comon-query pe-america.hosts "$CandidateForPE && (location==$NorthAmerica || location==$SouthAmerica)" name 5minload nameonly quiet

./comon-query pu-europe.hosts "$CandidateForPE && location==$Europe" name 5minload nameonly quiet
./comon-query pu-asia.hosts "$CandidateForPE && location==$Australasia" name 5minload nameonly quiet
./comon-query pu-america.hosts "$CandidateForPE && (location==$NorthAmerica || location==$SouthAmerica)" name 5minload nameonly quiet


wc --lines alive-planetlab.hosts

wc --lines pr-europe.hosts
wc --lines pr-asia.hosts
wc --lines pr-america.hosts

wc --lines pe-europe.hosts
wc --lines pe-asia.hosts
wc --lines pe-america.hosts

wc --lines pu-europe.hosts
wc --lines pu-asia.hosts
wc --lines pu-america.hosts
