#!/bin/bash

export Measurement=attack1
export Duration=900
export PRs=1
export PEs=10
export PUs=30
export AttackInterval=1
export Policy="LeastUsed"
export MaxBadPEReports=3
export JobInterval=60.0
export JobSize=10000000
export Attackers=1
export AttackType="registration"
export AttackIdentifier=0
export AttackReportUnreachableProbability=0.0


if [ ! -e "$Measurement" ] ; then
   mkdir "$Measurement"
fi
rm -rf "$Measurement/Results"
if [ ! -e "$Measurement/Results" ] ; then
   mkdir "$Measurement/Results"
fi
echo "--resultsdirectory=$Measurement/Results" >$Measurement/summary.input


for Policy in LeastUsed LeastUsedDegradation RoundRobin Random; do
   for AttackInterval in 0.1 0.5 15 30 50 ; do

      ID=$Duration-$Policy-$AttackInterval
      VARIABLES="Duration Policy AttackInterval"
      VALUES="$Duration \"$Policy\" $AttackInterval"


      echo ID=$ID
      if [ ! -e "$Measurement/$ID" ] ; then
         mkdir "$Measurement/$ID"
      fi


      cd "$Measurement/$ID"
      if [ ! -e status.txt ] ; then
         ../../attack-scenario1 && touch status.txt
      else
         echo "Skipping $ID -> already complete."
      fi
      cd ../..


      SCALARS="`find $Measurement/$ID -name "*.sca"`"
      for sca in $SCALARS ; do
         echo "--values=\"$VALUES\"" >>$Measurement/summary.input
         echo "--input=$sca" >>$Measurement/summary.input
      done
   done
done


cat $Measurement/summary.input | ../createsummary "$VARIABLES" -batch
