#!/bin/bash
# $Id$
#
# Thomas Dreibholz's PlanetLab Script Collection
# Copyright (C) 2005-2013 by Thomas Dreibholz
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
# Contact: dreibh@iem.uni-due.de


. ./planetlab-config


if [ $# -lt 2 ]; then
   echo "Usage: start-process [Process Name] [Server 1] {Server 2} ..."
   exit 1
fi
PROCNAME=$1
shift


while [ ! x$1 = "x" ] ; do
   SERVER=$1
   shift

   PIDFILE=$PROCNAME-$SERVER.pid
   if [ -e $PIDFILE ] ; then
      PID=`cat $PIDFILE`
      if ps -p `cat $PIDFILE` | grep ssh 1>/dev/null 2>/dev/null ; then
         echo "Processing $PIDFILE: sending SIGINT to $PID ..."
         kill $PID
         # echo STOP $! -- $PID -- $PIDFILE >$RANDOM-$RANDOM.td0
      else
         echo "Processing $PIDFILE: process is already gone."
         # echo DEAD $! -- $PIDFILE >$RANDOM-$RANDOM.td0
      fi
      rm $PIDFILE
   fi

done
