#!/bin/bash

. ./planetlab-config

SSH_NODE=merkur.planetlab.haw-hamburg.de
SSH_USER=$PLANETLAB_USER
SSH_KEY=$PLANETLAB_KEY

SERVICE_DIRECTORY="bin"
SERVICE_PRE_PROGRAM="sudo"
SERVICE_PROGRAM="registrar"
SERVICE_OPTS="$OPT_CSP -asap=[::]:3863 -enrp=[::]:9901 -asapannounce=off -enrpannounce=off"
SERVICE_INSTANCE_ID=1



SSH_NODE=localhost # merkur.planetlab.haw-hamburg.de
SSH_USER=dreibh # $PLANETLAB_USER
SSH_KEY=/home/dreibh/.ssh/test-key   # $PLANETLAB_KEY
SERVICE_PRE_PROGRAM=""
SERVICE_DIRECTORY="src/rsplib2/rsplib"

OPT_CSP="-cspserver=127.0.0.1 -cspinterval=333"
SERVICE_OPTS="$OPT_CSP -asap=[::]:3863 -enrp=[::]:9901 -asapannounce=off -enrpannounce=off"



rm x.cmd
./servicecontrol  restart  "./ssh-tool WriteCmd x.cmd"   $SSH_NODE $SSH_USER $SSH_KEY   $SERVICE_INSTANCE_ID $SERVICE_DIRECTORY $SERVICE_PROGRAM "$SERVICE_OPTS"   "$SERVICE_PRE_PROGRAM"
for i in 1 2 3 4 5 6 7 8 9 ; do
   ./servicecontrol  restart  "./ssh-tool WriteCmd x.cmd"   $SSH_NODE $SSH_USER $SSH_KEY   pe-$i $SERVICE_DIRECTORY server "-fractal -registrar=[::1]:3863 $OPT_CSP -fgpfailureafter=20"   "$SERVICE_PRE_PROGRAM"
done
./ssh-tool RunCmd x.cmd $SSH_NODE $SSH_USER $SSH_KEY
echo "$? done!"

# ./servicecontrol   status   $SSH_NODE $SSH_USER $SSH_KEY   $SERVICE_INSTANCE_ID $SERVICE_DIRECTORY $SERVICE_PROGRAM "$SERVICE_OPTS"   "$SERVICE_PRE_PROGRAM"


sleep 30


rm x.cmd
for i in 1 2 3 4 5 6 7 8 9 ; do
   ./servicecontrol  stop  "./ssh-tool WriteCmd x.cmd"   $SSH_NODE $SSH_USER $SSH_KEY   pe-$i $SERVICE_DIRECTORY server ""   "$SERVICE_PRE_PROGRAM"
done
./servicecontrol  stop   "./ssh-tool WriteCmd x.cmd"   $SSH_NODE $SSH_USER $SSH_KEY   $SERVICE_INSTANCE_ID $SERVICE_DIRECTORY $SERVICE_PROGRAM "$SERVICE_OPTS"   "$SERVICE_PRE_PROGRAM"
./ssh-tool RunCmd x.cmd $SSH_NODE $SSH_USER $SSH_KEY
