#!/bin/bash

. ./planetlab-config

SSH_NODE=merkur.planetlab.haw-hamburg.de
SSH_USER=$PLANETLAB_USER
SSH_KEY=$PLANETLAB_KEY

SSH_OPTS="-oConnectTimeout=7 -oConnectionAttempts=3 -oStrictHostKeyChecking=no -oPasswordAuthentication=no"

SERVICE_DIRECTORY="bin"
SERVICE_PROGRAM="registrar"
SERVICE_OPTS="$OPT_CSP -asapannounce=off -enrpannounce=off"
SERVICE_INSTANCE_ID=1

SERVICE_PIDFILE=$SSH_NODE-$SERVICE_PROGRAM-$SERVICE_INSTANCE_ID.pid
SERVICE_LOGFILE=$SSH_NODE-$SERVICE_PROGRAM-$SERVICE_INSTANCE_ID.log



# SSH_NODE=localhost # merkur.planetlab.haw-hamburg.de
# SSH_USER=dreibh # $PLANETLAB_USER
# SSH_KEY=/home/dreibh/.ssh/test-key   # $PLANETLAB_KEY
# SERVICE_DIRECTORY="src/rsplib2/rsplib"



./servicecontrol   start    $SSH_NODE $SSH_USER $SSH_KEY   $SERVICE_INSTANCE_ID $SERVICE_DIRECTORY $SERVICE_PROGRAM "$SERVICE_OPTS"
echo "$? done!"

sleep 30

./servicecontrol   stop     $SSH_NODE $SSH_USER $SSH_KEY   $SERVICE_INSTANCE_ID $SERVICE_DIRECTORY $SERVICE_PROGRAM "$SERVICE_OPTS"
