#!/usr/bin/env bash
# $Id$
# --------------------------------------------------------------------------
#
#              //===//   //=====   //===//   //       //   //===//
#             //    //  //        //    //  //       //   //    //
#            //===//   //=====   //===//   //       //   //===<<
#           //   \\         //  //        //       //   //    //
#          //     \\  =====//  //        //=====  //   //===//   Version III
#
# ------------- An Efficient RSerPool Prototype Implementation -------------
#
# Copyright (C) 2002-2026 by Thomas Dreibholz
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
# Contact: thomas.dreibholz@gmail.com

sed -e "s/<MaxIterations>100<\/MaxIterations>/<MaxIterations>1000<\/MaxIterations>/g" \
    -e "s/<MaxIterations>250<\/MaxIterations>/<MaxIterations>1000<\/MaxIterations>/g" \
    -e "s/<MaxIterations>400<\/MaxIterations>/<MaxIterations>1000<\/MaxIterations>/g" \
    -e "s/<MaxIterations>500<\/MaxIterations>/<MaxIterations>1000<\/MaxIterations>/g" \
    $1 >$1.new
mv $1.new $1
