#!/bin/bash

ip addr add 3ffe:ab:cd:ef:123:45:67:89a/64 dev dummy0
# ip addr 10.1.1.1/24 dev dummy0


i=0 ; while [ $i -lt 10 ] ; do
   echo "i=$i"

   # ip addr flush dev dummy0
   ip link set dummy0 down
   ip link set dummy0 up

   ./t3
   let i=$i+1
done
