#!/bin/bash -e

export TRAVIS_OS_NAME="linux"
export TOOL="pbuilder"

export DOCKER="debian:testing"
export VARIANT="debian"
# export DOCKER="ubuntu:trusty"
# export VARIANT="ubuntu"


SCRIPTS="before-install install build"

for script in $SCRIPTS ; do
   sudo env \
      TRAVIS_OS_NAME="$TRAVIS_OS_NAME" \
      DOCKER="$DOCKER" \
      VARIANT="$VARIANT" \
      TOOL="$TOOL" ci/${script}
done
