#!/bin/bash -e

export TRAVIS_OS_NAME="linux"
export COMPILER_C="clang"
export COMPILER_CXX="clang++"


# export DOCKER="debian:stretch"
# export VARIANT="debian"
# export TOOL="pbuilder"

export DOCKER="ubuntu:trusty"
export VARIANT="ubuntu"
export TOOL="compile"

# export DOCKER="fedora:30"
# export VARIANT="fedora"
# export TOOL="mock"


SCRIPTS="before-install install build test"
# SCRIPTS="install"

for script in $SCRIPTS ; do
   sudo env \
      TRAVIS_OS_NAME="$TRAVIS_OS_NAME" \
      DOCKER="$DOCKER" \
      VARIANT="$VARIANT" \
      COMPILER_C="$COMPILER_C" \
      COMPILER_CXX="$COMPILER_CXX" \
      TOOL="$TOOL" ci/${script}
done
