#!/usr/bin/env bash

INPUT="U01 U02 U03 U04 U05" #  U02 U03 U04 U05 U06 U07 U08 U09 U10 U11 U12 U13 U14 U15 U16 U17 U18 U19 U20 U21 U22"
OUTPUT="test1"

(
for m in $INPUT ; do
   echo "--values=$m LeastUsedDPF"
   echo "--input=messung6A-$m/pu-vectors.vec.bz2"
   echo "--values=$m LeastUsed"
   echo "--input=messung6B-$m/pu-vectors.vec.bz2"
done
) | ./combinesummaries $OUTPUT.data.bz2 "Measurement Policy"
