#!/usr/bin/env bash
# $Id: comon-host-selector 2279 2010-01-13 12:40:59Z dreibh $
#
# Thomas Dreibholz's PlanetLab Script Collection
# Copyright (C) 2005-2019 by Thomas Dreibholz
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
# Contact: dreibh@iem.uni-due.de


while [ $# -gt 0 ] ; do
   IP=$1 ; shift
   let a="($IP>>24) & 255"
   let b="($IP>>16) & 255"
   let c="($IP>>8) & 255"
   let d="($IP>>0) & 255"
   echo $a.$b.$c.$d
done
