#!/usr/bin/env bash
# $Id$
#
# Thomas Dreibholz's PlanetLab Script Collection
# Copyright (C) 2005-2024 by Thomas Dreibholz
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
# Contact: thomas.dreibholz@gmail.com


. ./planetlab-config

./comon-query alive-planetlab.hosts "resptime>0 && sshstatus<2h && (dns1udp<80 || dns2udp<80)" name name nameonly && \
cd .. && make && cd planetlab && \
./create-binaries && \
ls alive-planetlab.hosts | xargs -n 1 cat | grep "^[a-Z0-9]" | sort -u | xargs ./do-clearall && \
ls alive-planetlab.hosts | xargs -n 1 cat | grep "^[a-Z0-9]" | sort -u | xargs ./install-binaries
