#!/usr/bin/env bash

nohup ./run-attack-handleResolution-countermeasure-planetlabI >hc1 2>&1 &
sleep 23
nohup ./run-attack-handleResolution-countermeasure-planetlabII >hc2 2>&1 &
sleep 23
nohup ./run-attack-handleResolution-planetlabI >h0 2>&1 &
sleep 23
nohup ./run-attack-registration-countermeasure-planetlabI >rc1 2>&1 &
sleep 23
nohup ./run-attack-registration-countermeasure-planetlabII >rc2 2>&1 &
sleep 23
nohup ./run-attack-registration-planetlabI >r0 2>&1 &

wait

R --vanilla <plot-attack-handleResolution-countermeasure-planetlabII.R
R --vanilla <plot-attack-handleResolution-countermeasure-planetlabI.R
R --vanilla <plot-attack-handleResolution-planetlabI.R
R --vanilla <plot-attack-registration-countermeasure-planetlabII.R
R --vanilla <plot-attack-registration-countermeasure-planetlabI.R
R --vanilla <plot-attack-registration-planetlabI.R
