#!/usr/bin/env bash
# $Id$
#
# Thomas Dreibholz's PlanetLab Script Collection
# Copyright (C) 2005-2022 by Thomas Dreibholz
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
# Contact: dreibh@iem.uni-due.de


. ./planetlab-config

if [ $# -ne 1 ]; then
   echo "Usage: start-processes [Process Name]"
   exit 1
fi
PROCNAME=$1
shift


PIDFILES=`find . -name \"$PROCNAME-*.pid\"`
for PIDFILE in $PIDFILES; do
   PID=`cat $PIDFILE`
   if ps -p `cat $PIDFILE` | grep ssh 1>/dev/null 2>/dev/null ; then
      echo "Processing $PIDFILE: sending SIGINT to $PID ..."
      kill $PID
   else
      echo "Processing $PIDFILE: process is already gone."
   fi
   rm $PIDFILE
done
